import { defineConfig } from "tsdown";

export default defineConfig({
  fixedExtension: false,
  entry: [
    "./src/gateway/node-runtime-gateway.ts",
    "./src/gateway/graft-gateway-directory.ts",
    "./src/gateway/graft-gateway-directory-worker.ts",
    "./src/runtime/node-runtime-readiness.ts",
    "./src/graft/graft-control-bootstrap-cli.ts",
    "./src/graft/graft-control-database.ts",
    "./src/graft/graft-worker-directory.ts",
    "./src/graft/graft-control-store.ts",
    "./src/graft/graft-node-authority.ts",
    "./src/graft/graft-database-operations.ts",
    "./src/graft/graft-object-provisioning.ts",
    "./src/graft/graft-runtime-storage.ts",
    "./src/graft/graft-sqlite.ts",
    "./src/runtime/node-object-runtime.ts",
    "./src/runtime/node-object-runtime-host.ts",
    "./src/runtime/node-object-worker.ts",
    "./src/runtime/node-durable-object-state.ts",
    "./src/runtime/node-durable-object-storage.ts",
    "./src/runtime/node-runtime-object.ts",
    "./src/runtime/node-runtime-clock.ts",
    "./src/rpc/node-peer-rpc.ts",
    "./src/rpc/node-peer-websocket-server.ts",
    "./src/scheduling/node-alarm-scheduler.ts",
    "./src/scheduling/node-durable-hooks.ts",
    "./src/testing/node-runtime-scenario.ts",
  ],
  dts: true,
  unbundle: true,
});
