packages:
  - example-apps/*
  - example-fragments/*
  - apps/*
  - packages/*
  - packages-private/*
  - scripts

catalog:
  typescript: ^5.9.3
  vite: ^8.0.0
  vitest: ^4.1.0
  "@typescript/native-preview": "^7.0.0-dev.20260312.1"

onlyBuiltDependencies:
  - better-sqlite3
