packages:
  - example-apps/*
  - example-fragments/*
  - apps/*
  - packages/*
  - packages-private/*
  - scripts

catalog:
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  "@typescript/native-preview": "^7.0.0-dev.20260312.1"
  vite-plus: latest

onlyBuiltDependencies:
  - better-sqlite3
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
