import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    singleQuote: false,
    semi: true,
    tabWidth: 2,
    useTabs: false,
    printWidth: 100,
    proseWrap: "always",
    trailingComma: "all",
    sortImports: {
      sortSideEffects: true,
      internalPattern: ["~/", "@/"],
      customGroups: [
        {
          groupName: "test",
          selector: "import",
          elementNamePattern: ["*test", "vitest"],
        },
        {
          groupName: "fragno-package",
          selector: "external",
          elementNamePattern: ["@fragno-dev/*", "@rejot-dev/*"],
        },
        {
          groupName: "scoped-package",
          selector: "external",
          elementNamePattern: ["@*/*"],
        },
      ],
      groups: [
        ["side_effect", "side_effect_style"],
        "test",
        "builtin",
        "external",
        "fragno-package",
        "scoped-package",
        ["internal", "unknown", "subpath"],
        ["parent", "sibling", "index"],
        "style",
      ],
    },
    sortTailwindcss: {},
    sortPackageJson: true,
  },
  lint: {
    plugins: ["unicorn"],
    jsPlugins: [
      "./packages-private/oxlint-plugins/tsdown-exports-sync.js",
      "./packages-private/oxlint-plugins/fragment-dev-browser-exports.js",
      "./packages-private/oxlint-plugins/docs-icons-sync.js",
    ],
    env: {
      builtin: true,
    },
    ignorePatterns: [
      "**/samples/**",
      "**/dist/**",
      "**/node_modules/**",
      "**/build/**",
      "**/.react-router/**",
      "**/.svelte-kit/**",
      "**/.nuxt/**",
      "**/.turbo/**",
      "**/.next/**",
      "**/.output/**",
      "**/worker-configuration.d.ts",
      "**/.astro/**",
      "**/next-env.d.ts",
      "packages/docs/.source/**",
      "packages/fragment-workflows/workflows-smoke-artifacts/**",
      "specs/references/**",
      "packages/create/**",
      ".agents/**",
    ],
    rules: {
      "tsdown-exports-sync/exports-match": "error",
      "fragment-dev-browser-exports/exports-match": "error",
      "docs-icons-sync/used-icons": "error",
      "for-direction": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-unexpected-multiline": "off",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "@typescript-eslint/ban-ts-comment": "off",
      "no-array-constructor": "error",
      "@typescript-eslint/no-duplicate-enum-values": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-extra-non-null-assertion": "off",
      "@typescript-eslint/no-misused-new": "off",
      "@typescript-eslint/no-namespace": "off",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unnecessary-type-constraint": "off",
      "@typescript-eslint/no-unsafe-declaration-merging": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: false,
        },
      ],
      "@typescript-eslint/no-wrapper-object-types": "off",
      "@typescript-eslint/prefer-as-const": "off",
      "@typescript-eslint/prefer-namespace-keyword": "off",
      "@typescript-eslint/triple-slash-reference": "off",
      curly: "error",
      "unicorn/empty-brace-spaces": "error",
      "unicorn/no-nested-ternary": "off",
      "unicorn/number-literal-case": "off",
    },
    overrides: [
      {
        files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
        rules: {
          "no-class-assign": "error",
          "no-const-assign": "error",
          "no-dupe-class-members": "error",
          "no-dupe-keys": "error",
          "no-func-assign": "error",
          "no-import-assign": "error",
          "no-new-native-nonconstructor": "error",
          "no-obj-calls": "error",
          "no-redeclare": "error",
          "no-setter-return": "error",
          "no-this-before-super": "error",
          "no-unsafe-negation": "error",
          "no-var": "error",
          "no-with": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
});
