import { NextRequest, NextResponse } from "next/server";
import { isMarkdownPreferred, rewritePath } from "fumadocs-core/negotiation";

const { rewrite } = rewritePath("/docs/*path", "/api/markdown/*path");

/**
 * URL redirects for documentation refactor
 * Generated by LLM by passing old and new sitemap.xml
 * The refactor split the documentation up into two "layers", fragno and stripe.
 */
const REDIRECTS: Record<string, string> = {
  // Stripe fragment: /docs/our-fragments/stripe/* -> /docs/stripe/*
  "/docs/our-fragments/stripe/admin-hooks": "/docs/stripe/admin-hooks",
  "/docs/our-fragments/stripe/quickstart": "/docs/stripe/quickstart",
  "/docs/our-fragments/stripe/subscriptions": "/docs/stripe/subscriptions",
  "/docs/our-fragments/stripe/webhooks": "/docs/stripe/webhooks",

  // Framework docs: /docs/* -> /docs/fragno/*
  "/docs/frameworks": "/docs/fragno/reference/frameworks",
  "/docs/user-quick-start": "/docs/fragno/user-quick-start",
  "/docs/for-library-authors/faq": "/docs/fragno/for-library-authors/faq",
  "/docs/for-library-authors/getting-started": "/docs/fragno/for-library-authors/getting-started",
  "/docs/for-library-authors/testing": "/docs/fragno/for-library-authors/testing",
  "/docs/for-library-authors/troubleshooting": "/docs/fragno/for-library-authors/troubleshooting",
  "/docs/for-users/client-customization": "/docs/fragno/for-users/client-customization",
  "/docs/for-users/integrating-a-fragment": "/docs/fragno/for-users/integrating-a-fragment",
  "/docs/for-users/middleware": "/docs/fragno/for-users/middleware",
  "/docs/for-users/services": "/docs/fragno/for-users/services",
  "/docs/reference/cli": "/docs/fragno/reference/cli",
  "/docs/reference/frameworks": "/docs/fragno/reference/frameworks",
  "/docs/reference/glossary": "/docs/fragno/reference/glossary",
  "/docs/for-library-authors/database-integration/defining-schemas":
    "/docs/fragno/for-library-authors/database-integration/defining-schemas",
  "/docs/for-library-authors/database-integration/overview":
    "/docs/fragno/for-library-authors/database-integration/overview",
  "/docs/for-library-authors/database-integration/querying":
    "/docs/fragno/for-library-authors/database-integration/querying",
  "/docs/for-library-authors/features/client-state-management":
    "/docs/fragno/for-library-authors/features/client-state-management",
  "/docs/for-library-authors/features/code-splitting":
    "/docs/fragno/for-library-authors/features/code-splitting",
  "/docs/for-library-authors/features/dependencies-and-services":
    "/docs/fragno/for-library-authors/features/dependencies-and-services",
  "/docs/for-library-authors/features/route-definition":
    "/docs/fragno/for-library-authors/features/route-definition",
  "/docs/for-users/client-frameworks/react": "/docs/fragno/for-users/client-frameworks/react",
  "/docs/for-users/client-frameworks/solid-js": "/docs/fragno/for-users/client-frameworks/solid-js",
  "/docs/for-users/client-frameworks/svelte": "/docs/fragno/for-users/client-frameworks/svelte",
  "/docs/for-users/client-frameworks/vanilla-js":
    "/docs/fragno/for-users/client-frameworks/vanilla-js",
  "/docs/for-users/client-frameworks/vue": "/docs/fragno/for-users/client-frameworks/vue",
  "/docs/for-users/database-fragments/drizzle": "/docs/fragno/for-users/database-fragments/drizzle",
  "/docs/for-users/database-fragments/kysely": "/docs/fragno/for-users/database-fragments/kysely",
  "/docs/for-users/database-fragments/overview":
    "/docs/fragno/for-users/database-fragments/overview",
};

export function middleware(request: NextRequest) {
  // Check for redirects first
  const redirectTarget = REDIRECTS[request.nextUrl.pathname];
  if (redirectTarget) {
    const destination = new URL(redirectTarget, request.url);
    console.debug(`Redirecting ${request.nextUrl.pathname} to ${destination.pathname}`);
    return NextResponse.redirect(destination, { status: 308 });
  }
  if (isMarkdownPreferred(request)) {
    // Accept header is text/markdown
    const result = rewrite(request.nextUrl.pathname);

    if (result) {
      return NextResponse.rewrite(new URL(result, request.nextUrl));
    }
  }

  if (request.nextUrl.pathname.endsWith(".md") || request.nextUrl.pathname.endsWith(".mdx")) {
    const pathWithoutExtension = request.nextUrl.pathname.replace(/\.mdx?$/, "");

    // Special case: /docs.md or /docs.mdx should map to /api/markdown (the index)
    if (pathWithoutExtension === "/docs") {
      return NextResponse.rewrite(new URL("/api/markdown", request.nextUrl));
    }

    const result = rewrite(pathWithoutExtension);

    if (result) {
      return NextResponse.rewrite(new URL(result, request.nextUrl));
    }
  }

  return NextResponse.next();
}
