import { describe, expect, it } from "vitest";
import { column, idColumn, referenceColumn, schema } from "../../schema/create";
import { internalSchema } from "../../fragments/internal-fragment";
import { generateSchema } from "./generate";

const blogSchema = schema((s) => {
  return s
    .addTable("users", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("email", column("string"))
        .addColumn(
          "createdAt",
          column("timestamp").defaultTo((b) => b.now()),
        )
        .addColumn("birthDate", column("date").nullable())
        .addColumn("profile", column("json").nullable())
        .addColumn("bigScore", column("bigint"))
        .addColumn("invitedBy", referenceColumn().nullable())
        .createIndex("idx_email", ["email"], { unique: true });
    })
    .addTable("posts", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("title", column("string"))
        .addColumn("authorId", referenceColumn())
        .addColumn("editorId", referenceColumn().nullable())
        .addColumn("publishedAt", column("timestamp").nullable())
        .createIndex("idx_title", ["title"]);
    })
    .addReference("author", {
      type: "one",
      from: { table: "posts", column: "authorId" },
      to: { table: "users", column: "id" },
    })
    .addReference("editor", {
      type: "one",
      from: { table: "posts", column: "editorId" },
      to: { table: "users", column: "id" },
    })
    .addReference("inviter", {
      type: "one",
      from: { table: "users", column: "invitedBy" },
      to: { table: "users", column: "id" },
    })
    .addReference("posts", {
      type: "many",
      from: { table: "users", column: "id" },
      to: { table: "posts", column: "authorId" },
    });
});

describe("generateSchema (Prisma)", () => {
  it("should generate SQLite Prisma schema", () => {
    const generated = generateSchema(
      [
        { namespace: "", schema: internalSchema },
        { namespace: "blog", schema: blogSchema },
      ],
      "sqlite",
      { sqliteProfile: "prisma" },
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.\n// Provider: sqlite\n// Namespaces: blog\n\nmodel FragnoDbSettings {\n  id String @unique @default(cuid())\n  key String\n  value String\n  _internalId Int @id @default(autoincrement())\n  _version Int @default(0)\n  @@unique([key], map: "unique_key")\n  @@map("fragno_db_settings")\n}\n\nmodel FragnoHooks {\n  id String @unique @default(cuid())\n  namespace String\n  hookName String\n  payload Json\n  status String\n  attempts Int @default(0)\n  maxAttempts Int @default(5)\n  lastAttemptAt DateTime?\n  nextRetryAt DateTime?\n  error String?\n  createdAt DateTime @default(now())\n  nonce String\n  _internalId Int @id @default(autoincrement())\n  _version Int @default(0)\n  @@index([namespace, status, nextRetryAt], map: "idx_namespace_status_retry")\n  @@index([nonce], map: "idx_nonce")\n  @@map("fragno_hooks")\n}\n\nmodel Posts_blog {\n  id String @unique @default(cuid())\n  title String\n  authorId Int\n  editorId Int?\n  publishedAt DateTime?\n  _internalId Int @id @default(autoincrement())\n  _version Int @default(0)\n  author Users_blog @relation("blog_posts_author_users", fields: [authorId], references: [_internalId], map: "fk_posts_users_author_blog")\n  editor Users_blog? @relation("blog_posts_editor_users", fields: [editorId], references: [_internalId], map: "fk_posts_users_editor_blog")\n  @@index([title], map: "idx_title_blog")\n  @@map("posts_blog")\n}\n\nmodel Users_blog {\n  id String @unique @default(cuid())\n  email String\n  createdAt DateTime @default(now())\n  birthDate DateTime?\n  profile Json?\n  bigScore BigInt\n  invitedBy Int?\n  _internalId Int @id @default(autoincrement())\n  _version Int @default(0)\n  inviter Users_blog? @relation("blog_users_inviter_users", fields: [invitedBy], references: [_internalId], map: "fk_users_users_inviter_blog")\n  posts Posts_blog[] @relation("blog_posts_author_users")\n  posts_editor Posts_blog[] @relation("blog_posts_editor_users")\n  users Users_blog[] @relation("blog_users_inviter_users")\n  @@unique([email], map: "idx_email_blog")\n  @@map("users_blog")\n}"
    `);
  });

  it("should generate PostgreSQL (PGLite) Prisma schema", () => {
    const generated = generateSchema(
      [
        { namespace: "", schema: internalSchema },
        { namespace: "blog", schema: blogSchema },
      ],
      "postgresql",
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.\n// Provider: postgresql\n// Namespaces: blog\n\nmodel FragnoDbSettings {\n  id String @unique @default(cuid()) @db.VarChar(30)\n  key String\n  value String\n  _internalId BigInt @id @default(autoincrement())\n  _version Int @default(0)\n  @@unique([key], map: "unique_key")\n  @@map("fragno_db_settings")\n}\n\nmodel FragnoHooks {\n  id String @unique @default(cuid()) @db.VarChar(30)\n  namespace String\n  hookName String\n  payload Json @db.Json\n  status String\n  attempts Int @default(0)\n  maxAttempts Int @default(5)\n  lastAttemptAt DateTime?\n  nextRetryAt DateTime?\n  error String?\n  createdAt DateTime @default(now())\n  nonce String\n  _internalId BigInt @id @default(autoincrement())\n  _version Int @default(0)\n  @@index([namespace, status, nextRetryAt], map: "idx_namespace_status_retry")\n  @@index([nonce], map: "idx_nonce")\n  @@map("fragno_hooks")\n}\n\nmodel Posts_blog {\n  id String @unique @default(cuid()) @db.VarChar(30)\n  title String\n  authorId BigInt\n  editorId BigInt?\n  publishedAt DateTime?\n  _internalId BigInt @id @default(autoincrement())\n  _version Int @default(0)\n  author Users_blog @relation("blog_posts_author_users", fields: [authorId], references: [_internalId], map: "fk_posts_users_author_blog")\n  editor Users_blog? @relation("blog_posts_editor_users", fields: [editorId], references: [_internalId], map: "fk_posts_users_editor_blog")\n  @@index([title], map: "idx_title_blog")\n  @@map("posts_blog")\n}\n\nmodel Users_blog {\n  id String @unique @default(cuid()) @db.VarChar(30)\n  email String\n  createdAt DateTime @default(now())\n  birthDate DateTime? @db.Date\n  profile Json? @db.Json\n  bigScore BigInt\n  invitedBy BigInt?\n  _internalId BigInt @id @default(autoincrement())\n  _version Int @default(0)\n  inviter Users_blog? @relation("blog_users_inviter_users", fields: [invitedBy], references: [_internalId], map: "fk_users_users_inviter_blog")\n  posts Posts_blog[] @relation("blog_posts_author_users")\n  posts_editor Posts_blog[] @relation("blog_posts_editor_users")\n  users Users_blog[] @relation("blog_users_inviter_users")\n  @@unique([email], map: "idx_email_blog")\n  @@map("users_blog")\n}"
    `);
  });
});
