import unpluginFragno from "@fragno-dev/unplugin-fragno/rollup";
import { defineConfig } from "tsdown";

export default defineConfig([
  {
    fixedExtension: false,
    ignoreWatch: ["./dist"],
    entry: [
      "./src/index.ts",
      "./src/schema.ts",
      "./src/workflow.ts",
      "./src/debug-log.ts",
      "./src/stream-step-emissions.ts",
      "./src/step-identity.ts",
      "./src/remote-workflow.ts",
      "./src/instance-ref.ts",
      "./src/runner/step-live-pump.ts",
      "./src/scenario.ts",
      "./src/test.ts",
      "./src/client/react.ts",
      "./src/client/svelte.ts",
      "./src/client/solid.ts",
      "./src/client/vanilla.ts",
      "./src/client/vue.ts",
    ],
    dts: true,
    platform: "node",
    outDir: "./dist/node",
    unbundle: true,
    deps: { neverBundle: [/^@fragno-dev\/test/, /^@fragno-dev\/db/] },
    plugins: [unpluginFragno({ platform: "node" })],
  },
  {
    fixedExtension: false,
    ignoreWatch: ["./dist"],
    entry: [
      "./src/schema.ts",
      "./src/client/clients.ts",
      "./src/client/react.ts",
      "./src/client/svelte.ts",
      "./src/client/solid.ts",
      "./src/client/vanilla.ts",
      "./src/client/vue.ts",
    ],
    dts: true,
    platform: "browser",
    outDir: "./dist/browser",
    unbundle: true,
    plugins: [unpluginFragno({ platform: "browser" })],
    deps: { alwaysBundle: [/^@fragno-dev\/core\//] },
  },
]);
