import unpluginFragno from "@fragno-dev/unplugin-fragno/rollup";
import { defineConfig } from "tsdown";

export default defineConfig([
  {
    ignoreWatch: ["./dist"],
    entry: [
      "./src/index.ts",
      "./src/workflow.ts",
      "./src/debug-log.ts",
      "./src/stream-step-emissions.ts",
      "./src/instance-ref.ts",
      "./src/runner/step-live-pump.ts",
      "./src/scenario.ts",
      "./src/test.ts",
      "./src/client/react.ts",
      "./src/client/svelte.ts",
      "./src/client/solid.ts",
      "./src/client/vanilla.ts",
      "./src/client/vue.ts",
    ],
    dts: true,
    platform: "node",
    outDir: "./dist/node",
    unbundle: true,
    external: [/^@fragno-dev\/test/, /^@fragno-dev\/db/],
    plugins: [unpluginFragno({ platform: "node" })],
  },
  {
    ignoreWatch: ["./dist"],
    entry: [
      "./src/client/clients.ts",
      "./src/client/react.ts",
      "./src/client/svelte.ts",
      "./src/client/solid.ts",
      "./src/client/vanilla.ts",
      "./src/client/vue.ts",
    ],
    dts: true,
    platform: "browser",
    outDir: "./dist/browser/client",
    unbundle: true,
    plugins: [unpluginFragno({ platform: "browser" })],
    noExternal: [/^@fragno-dev\/core\//],
  },
  {
    ignoreWatch: ["./dist"],
    entry: ["./src/dynamic-runtime.ts"],
    dts: true,
    platform: "neutral",
    target: "es2022",
    outDir: "./dist/node-bundle",
    external: [/^cloudflare:workers$/],
    noExternal: [
      /^@fragno-dev\/core/,
      /^@fragno-dev\/db/,
      /^@fragno-dev\/workflows/,
      /^@nanostores\/query/,
      /^@nanostores\/solid/,
      /^@standard-schema\/spec/,
      /^kysely/,
      /^nanostores/,
      /^rou3/,
      /^superjson/,
      /^zod/,
    ],
    plugins: [unpluginFragno({ platform: "node" })],
  },
]);
