import type { NamingResolver } from "../naming/sql-naming";
import type { AnyTable, AnyColumn } from "../schema/create";
import { FragnoId, FragnoReference, getTableForeignKey } from "../schema/create";
import {
  generateDatabaseDefault,
  generateRuntimeDefault,
  type RuntimeDefaultContext,
} from "./column-defaults";

/**
 * Marker class for reference column values that need subquery resolution.
 * When a reference column receives a string (external ID), this marker tells
 * the query builder to generate a subquery to look up the internal ID.
 * @internal
 */
export class ReferenceSubquery {
  readonly #referencedTable: AnyTable;
  readonly #externalIdValue: string;

  constructor(referencedTable: AnyTable, externalIdValue: string) {
    this.#referencedTable = referencedTable;
    this.#externalIdValue = externalIdValue;
  }

  get referencedTable() {
    return this.#referencedTable;
  }

  get externalIdValue() {
    return this.#externalIdValue;
  }
}

/**
 * Resolves FragnoId or FragnoReference objects to their appropriate primitive values.
 *
 * This function handles the Fragno ID system's conversion to database values:
 * - FragnoReference objects are resolved to their internal IDs
 * - FragnoId objects are resolved based on the column role:
 *   - external-id: uses the external ID
 *   - internal-id: uses the internal ID (must be present)
 *   - reference: uses databaseId (internal ID if available, else external ID)
 *   - other: uses the external ID by default
 *
 * @param value - The value to resolve (may be FragnoId, FragnoReference, or any other value)
 * @param col - The column schema definition
 * @returns The resolved primitive value, or the original value if not a FragnoId/FragnoReference
 * @throws Error if internal ID is required but not available
 * @internal
 */
export function resolveFragnoIdValue(value: unknown, col: AnyColumn): unknown {
  // Handle FragnoReference objects (for reference columns)
  if (value instanceof FragnoReference) {
    return value.internalId;
  }

  // Handle FragnoId objects
  if (value instanceof FragnoId) {
    // For external ID columns, use the external ID
    if (col.role === "external-id") {
      return value.externalId;
    }
    // For internal ID columns, use the internal ID (must be present)
    if (col.role === "internal-id") {
      if (value.internalId === undefined) {
        throw new Error(`FragnoId must have internalId for internal-id column ${col.name}`);
      }
      return value.internalId;
    }
    // For reference columns, prefer internal ID if available, else external ID
    if (col.role === "reference") {
      return value.databaseId;
    }
    // Default to external ID for other columns
    return value.externalId;
  }

  return value;
}

/**
 * Resolves application-owned defaults once so execution and durable side effects share values.
 * Database-owned defaults remain omitted for the database and outbox builder to materialize.
 *
 * @internal
 */
export function materializeRuntimeCreateValues<TValues extends Record<string, unknown>>(
  values: TValues,
  table: AnyTable,
  runtimeDefaults: RuntimeDefaultContext = {},
): TValues {
  const materialized: Record<string, unknown> = { ...values };

  for (const [columnName, column] of Object.entries(table.columns)) {
    if (column.role === "internal-id" || materialized[columnName] !== undefined) {
      continue;
    }

    const generated = generateRuntimeDefault(column, runtimeDefaults);
    if (generated !== undefined) {
      materialized[columnName] = generated;
    }
  }

  return materialized as TValues;
}

/**
 * Encodes application values into resolved database-column values without driver serialization.
 */
export function encodeValues(
  values: Record<string, unknown>,
  table: AnyTable,
  generateDefault: boolean,
  runtimeDefaults: RuntimeDefaultContext = {},
  resolver?: NamingResolver,
): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  const resolvedValues = generateDefault
    ? materializeRuntimeCreateValues(values, table, runtimeDefaults)
    : values;

  for (const k in table.columns) {
    const col = table.columns[k];

    // Skip internal ID - never provided by user, auto-generated by database
    if (col.role === "internal-id") {
      continue;
    }

    const value = resolvedValues[k];
    if (value !== undefined) {
      const physicalColumnName = resolver ? resolver.getColumnName(table.name, col.name) : col.name;

      // Handle reference columns: strings or FragnoIds without internal IDs need subqueries
      if (col.role === "reference") {
        let needsSubquery = false;
        let externalIdForSubquery: string | undefined;

        if (typeof value === "string") {
          // String external ID - needs subquery
          needsSubquery = true;
          externalIdForSubquery = value;
        } else if (value instanceof FragnoId && value.internalId === undefined) {
          // FragnoId without internal ID - needs subquery
          needsSubquery = true;
          externalIdForSubquery = value.externalId;
        } else if (value instanceof FragnoId && value.internalId !== undefined) {
          // FragnoId with internal ID - use it directly (will be serialized later)
          result[physicalColumnName] = value.internalId;
          continue;
        } else if (value instanceof FragnoReference) {
          // FragnoReference - use internal ID directly (will be serialized later)
          result[physicalColumnName] = value.internalId;
          continue;
        }

        if (needsSubquery) {
          const foreignKey = getTableForeignKey(table, k);
          if (foreignKey) {
            result[physicalColumnName] = new ReferenceSubquery(
              foreignKey.referencedTable,
              externalIdForSubquery!,
            );
            continue;
          }
          throw new Error(`Reference column ${k} not found in table ${table.name}`);
        }
      }

      // Resolve FragnoId/FragnoReference to primitive values (serialization happens later)
      const resolvedValue = resolveFragnoIdValue(value, col);
      result[physicalColumnName] = resolvedValue;
    }
  }

  return result;
}

/**
 * Encode values and apply database defaults in-process.
 *
 * This is intended for adapters that cannot rely on database DEFAULT constraints,
 * such as the in-memory adapter.
 *
 * @internal
 */
export function encodeValuesWithDbDefaults(
  values: Record<string, unknown>,
  table: AnyTable,
  runtimeDefaults: RuntimeDefaultContext = {},
  resolver?: NamingResolver,
): Record<string, unknown> {
  const resolved = encodeValues(values, table, true, runtimeDefaults, resolver);

  for (const columnKey of Object.keys(table.columns)) {
    const column = table.columns[columnKey];
    if (column.role === "internal-id") {
      continue;
    }

    const physicalColumnName = resolver
      ? resolver.getColumnName(table.name, column.name)
      : column.name;
    if (Object.prototype.hasOwnProperty.call(resolved, physicalColumnName)) {
      continue;
    }

    const fallback = generateDatabaseDefault(column, runtimeDefaults);
    if (fallback !== undefined) {
      resolved[physicalColumnName] = fallback;
    }
  }

  return resolved;
}
