import { describe, expect, it } from "vitest";

import { sqliteStorageDefault, sqliteStoragePrisma } from "../adapters/generic-sql/sqlite-storage";
import { internalSchema } from "../fragments/internal-fragment";
import { column, idColumn, referenceColumn, schema } from "../schema/create";
import { generatePrismaSchema } from "./prisma";

const blogSchema = schema("blog", (s) => {
  return s
    .addTable("users", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("email", column("string"))
        .addColumn(
          "createdAt",
          column("timestamp").defaultTo((b) => b.now()),
        )
        .addColumn("birthDate", column("date").nullable())
        .addColumn("profile", column("json").nullable())
        .addColumn("bigScore", column("bigint"))
        .addColumn("reputation", column("decimal"))
        .addColumn("invitedBy", referenceColumn({ table: "users" }).nullable())
        .createIndex("idx_email", ["email"], { unique: true });
    })
    .addTable("posts", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("title", column("string"))
        .addColumn("authorId", referenceColumn({ table: "users" }))
        .addColumn("editorId", referenceColumn({ table: "users" }).nullable())
        .addColumn("publishedAt", column("timestamp").nullable())
        .createIndex("idx_title", ["title"]);
    });
});

const weirdNamesSchema = schema("weirdnames", (s) => {
  return s.addTable("user-profiles", (t) => {
    return t
      .addColumn("id", idColumn())
      .addColumn("user-id", column("string"))
      .addColumn("display name", column("string").nullable())
      .createIndex("user-id-index", ["user-id"]);
  });
});

const relationNamingSchema = schema("relationnaming", (s) => {
  return s
    .addTable("users", (t) => {
      return t.addColumn("id", idColumn()).addColumn("name", column("string"));
    })
    .addTable("posts", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("author_id", referenceColumn({ table: "users" }))
        .addColumn("editor_id", referenceColumn({ table: "users" }).nullable());
    })
    .addTable("comments", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("post_id", referenceColumn({ table: "posts" }))
        .addColumn("parent_id", referenceColumn({ table: "comments" }).nullable());
    })
    .addTable("follows", (t) => {
      return t
        .addColumn("id", idColumn())
        .addColumn("follower_id", referenceColumn({ table: "users" }))
        .addColumn("followee_id", referenceColumn({ table: "users" }));
    });
});

describe("generatePrismaSchema", () => {
  it("should generate stable ordering for internal models and schemas", () => {
    const alphaSchema = schema("alpha", (s) => {
      return s
        .addTable("zeta", (t) => t.addColumn("id", idColumn()))
        .addTable("alpha", (t) => t.addColumn("id", idColumn()));
    });

    const bravoSchema = schema("bravo", (s) => {
      return s.addTable("bravo", (t) => t.addColumn("id", idColumn()));
    });

    const generated = generatePrismaSchema(
      [
        { namespace: "alpha", schema: bravoSchema },
        { namespace: null, schema: internalSchema },
        { namespace: "zulu", schema: alphaSchema },
      ],
      "sqlite",
      { sqliteStorageMode: sqliteStoragePrisma },
    );

    const settingsIndex = generated.indexOf("model FragnoDbSettings");
    const hooksIndex = generated.indexOf("model FragnoHooks");
    const outboxIndex = generated.indexOf("model FragnoDbOutbox");
    const alphaIndex = generated.indexOf("model Alpha_zulu");
    const zetaIndex = generated.indexOf("model Zeta_zulu");
    const bravoIndex = generated.indexOf("model Bravo_alpha");

    expect(settingsIndex).toBeGreaterThanOrEqual(0);
    expect(hooksIndex).toBeGreaterThanOrEqual(0);
    expect(outboxIndex).toBeGreaterThanOrEqual(0);
    expect(alphaIndex).toBeGreaterThanOrEqual(0);
    expect(zetaIndex).toBeGreaterThanOrEqual(0);
    expect(bravoIndex).toBeGreaterThanOrEqual(0);

    expect(outboxIndex).toBeLessThan(settingsIndex);
    expect(settingsIndex).toBeLessThan(hooksIndex);
    expect(hooksIndex).toBeLessThan(alphaIndex);
    expect(alphaIndex).toBeLessThan(zetaIndex);
    expect(zetaIndex).toBeLessThan(bravoIndex);
  });
  it("should generate SQLite Prisma schema", () => {
    const generated = generatePrismaSchema(
      [
        { namespace: null, schema: internalSchema },
        { namespace: "blog", schema: blogSchema },
      ],
      "sqlite",
      { sqliteStorageMode: sqliteStoragePrisma },
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.
      // Provider: sqlite
      // Namespaces: blog

      model FragnoDbOutbox {
        id String @default(cuid())
        versionstamp String
        uowId String
        payload Json
        refMap Json?
        createdAt DateTime @default(now())
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@index([_shard, uowId], map: "idx_fragno_db_outbox_idx_outbox_uow_733c7f90")
        @@unique([_shard, versionstamp], map: "uidx_fragno_db_outbox_idx_outbox_versionstamp_37972a68")
        @@unique([_shard, id], map: "uidx_fragno_db_outbox__fragno_fragno_db_outbox_shard_ex316604b3")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_outbox__fragno_fragno_db_outbox_shard_in05b5be19")
        @@map("fragno_db_outbox")
      }

      model FragnoDbOutboxMutations {
        id String @default(cuid())
        entryVersionstamp String
        mutationVersionstamp String
        uowId String
        schema String
        table String
        externalId String?
        op String
        createdAt DateTime @default(now())
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        payload Json
        @@index([_shard, entryVersionstamp], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_entf896150d")
        @@index([_shard, entryVersionstamp, mutationVersionstamp], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_entea64c823")
        @@index([_shard, schema, table, externalId, entryVersionstamp], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_key16922fb2")
        @@index([_shard, uowId], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_uowa7a0749c")
        @@unique([_shard, id], map: "uidx_fragno_db_outbox_mutations__fragno_fragno_db_outbo4efa558a")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_outbox_mutations__fragno_fragno_db_outbo153d0338")
        @@map("fragno_db_outbox_mutations")
      }

      model FragnoDbSettings {
        id String @default(cuid())
        key String
        value String
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@unique([_shard, key], map: "uidx_fragno_db_settings_unique_key_09269db3")
        @@unique([_shard, id], map: "uidx_fragno_db_settings__fragno_fragno_db_settings_sharad08018c")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_settings__fragno_fragno_db_settings_shar72e2f194")
        @@map("fragno_db_settings")
      }

      model FragnoDbSyncRequests {
        id String @default(cuid())
        requestId String
        status String
        confirmedCommandIds Json
        conflictCommandId String?
        baseVersionstamp String?
        lastVersionstamp String?
        createdAt DateTime @default(now())
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@unique([_shard, requestId], map: "uidx_fragno_db_sync_requests_idx_sync_request_id_a352b2bb")
        @@unique([_shard, id], map: "uidx_fragno_db_sync_requests__fragno_fragno_db_sync_reqc4d044dd")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_sync_requests__fragno_fragno_db_sync_reqf174efb0")
        @@map("fragno_db_sync_requests")
      }

      model FragnoHooks {
        id String @default(cuid())
        namespace String
        hookName String
        payload Json
        status String
        attempts Int @default(0)
        maxAttempts Int @default(5)
        lastAttemptAt DateTime?
        nextRetryAt DateTime?
        error String?
        createdAt DateTime @default(now())
        nonce String
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        propagationContext Json?
        @@index([_shard, namespace, createdAt, id], map: "idx_fragno_hooks_idx_namespace_created_at_e489a066")
        @@index([_shard, namespace, status, lastAttemptAt], map: "idx_fragno_hooks_idx_namespace_status_last_attempt_f6aacab3")
        @@index([_shard, namespace, status, nextRetryAt], map: "idx_fragno_hooks_idx_namespace_status_retry_b66b1168")
        @@index([_shard, nonce], map: "idx_fragno_hooks_idx_nonce_90c97cf1")
        @@unique([_shard, id], map: "uidx_fragno_hooks__fragno_fragno_hooks_shard_external_ide396e3b")
        @@unique([_shard, _internalId], map: "uidx_fragno_hooks__fragno_fragno_hooks_shard_internal_i9c5d8377")
        @@map("fragno_hooks")
      }

      model Posts_blog {
        id String @default(cuid())
        title String
        authorId Int
        editorId Int?
        publishedAt DateTime?
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        author Users_blog @relation("blog_posts_author_users", fields: [_shard, authorId], references: [_shard, _internalId], map: "fk_posts_users_posts_authorId_fk_blog_7969e40f")
        editor Users_blog? @relation("blog_posts_editor_users", fields: [_shard, editorId], references: [_shard, _internalId], map: "fk_posts_users_posts_editorId_fk_blog_3e07e080")
        @@index([_shard, title], map: "idx_posts_idx_title_blog_f90cbb7e")
        @@unique([_shard, id], map: "uidx_posts__fragno_posts_shard_external_id_blog_1548d897")
        @@unique([_shard, _internalId], map: "uidx_posts__fragno_posts_shard_internal_id_blog_68dfcd25")
        @@map("posts_blog")
      }

      model Users_blog {
        id String @default(cuid())
        email String
        createdAt DateTime @default(now())
        birthDate DateTime?
        profile Json?
        bigScore BigInt
        reputation Float
        invitedBy Int?
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        invitedBy_1 Users_blog? @relation("blog_users_invitedBy_users", fields: [_shard, invitedBy], references: [_shard, _internalId], map: "fk_users_users_users_invitedBy_fk_blog_2f6bd5fd")
        posts Posts_blog[] @relation("blog_posts_author_users")
        posts_editor Posts_blog[] @relation("blog_posts_editor_users")
        users Users_blog[] @relation("blog_users_invitedBy_users")
        @@unique([_shard, email], map: "uidx_users_idx_email_blog_4468050e")
        @@unique([_shard, id], map: "uidx_users__fragno_users_shard_external_id_blog_347b9685")
        @@unique([_shard, _internalId], map: "uidx_users__fragno_users_shard_internal_id_blog_1020970d")
        @@map("users_blog")
      }"
    `);
  });

  it("should reflect alterColumn nullable changes", () => {
    const alteredSchema = schema("altered", (s) => {
      return s
        .addTable("users", (t) => {
          return t.addColumn("id", idColumn()).addColumn("name", column("string"));
        })
        .alterTable("users", (t) => {
          return t.alterColumn("name").nullable();
        });
    });

    const generated = generatePrismaSchema(
      [{ namespace: "altered", schema: alteredSchema }],
      "sqlite",
      { sqliteStorageMode: sqliteStoragePrisma },
    );

    expect(generated).toContain("name String?");
  });

  it("should generate SQLite Prisma schema for default storage mode", () => {
    const generated = generatePrismaSchema(
      [
        { namespace: null, schema: internalSchema },
        { namespace: "blog", schema: blogSchema },
      ],
      "sqlite",
      { sqliteStorageMode: sqliteStorageDefault },
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.
      // Provider: sqlite
      // Namespaces: blog

      model FragnoDbOutbox {
        id String @default(cuid())
        versionstamp String
        uowId String
        payload Json
        refMap Json?
        createdAt Int @default(dbgenerated("CURRENT_TIMESTAMP"))
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@index([_shard, uowId], map: "idx_fragno_db_outbox_idx_outbox_uow_733c7f90")
        @@unique([_shard, versionstamp], map: "uidx_fragno_db_outbox_idx_outbox_versionstamp_37972a68")
        @@unique([_shard, id], map: "uidx_fragno_db_outbox__fragno_fragno_db_outbox_shard_ex316604b3")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_outbox__fragno_fragno_db_outbox_shard_in05b5be19")
        @@map("fragno_db_outbox")
      }

      model FragnoDbOutboxMutations {
        id String @default(cuid())
        entryVersionstamp String
        mutationVersionstamp String
        uowId String
        schema String
        table String
        externalId String?
        op String
        createdAt Int @default(dbgenerated("CURRENT_TIMESTAMP"))
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        payload Json
        @@index([_shard, entryVersionstamp], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_entf896150d")
        @@index([_shard, entryVersionstamp, mutationVersionstamp], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_entea64c823")
        @@index([_shard, schema, table, externalId, entryVersionstamp], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_key16922fb2")
        @@index([_shard, uowId], map: "idx_fragno_db_outbox_mutations_idx_outbox_mutations_uowa7a0749c")
        @@unique([_shard, id], map: "uidx_fragno_db_outbox_mutations__fragno_fragno_db_outbo4efa558a")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_outbox_mutations__fragno_fragno_db_outbo153d0338")
        @@map("fragno_db_outbox_mutations")
      }

      model FragnoDbSettings {
        id String @default(cuid())
        key String
        value String
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@unique([_shard, key], map: "uidx_fragno_db_settings_unique_key_09269db3")
        @@unique([_shard, id], map: "uidx_fragno_db_settings__fragno_fragno_db_settings_sharad08018c")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_settings__fragno_fragno_db_settings_shar72e2f194")
        @@map("fragno_db_settings")
      }

      model FragnoDbSyncRequests {
        id String @default(cuid())
        requestId String
        status String
        confirmedCommandIds Json
        conflictCommandId String?
        baseVersionstamp String?
        lastVersionstamp String?
        createdAt Int @default(dbgenerated("CURRENT_TIMESTAMP"))
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@unique([_shard, requestId], map: "uidx_fragno_db_sync_requests_idx_sync_request_id_a352b2bb")
        @@unique([_shard, id], map: "uidx_fragno_db_sync_requests__fragno_fragno_db_sync_reqc4d044dd")
        @@unique([_shard, _internalId], map: "uidx_fragno_db_sync_requests__fragno_fragno_db_sync_reqf174efb0")
        @@map("fragno_db_sync_requests")
      }

      model FragnoHooks {
        id String @default(cuid())
        namespace String
        hookName String
        payload Json
        status String
        attempts Int @default(0)
        maxAttempts Int @default(5)
        lastAttemptAt Int?
        nextRetryAt Int?
        error String?
        createdAt Int @default(dbgenerated("CURRENT_TIMESTAMP"))
        nonce String
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        propagationContext Json?
        @@index([_shard, namespace, createdAt, id], map: "idx_fragno_hooks_idx_namespace_created_at_e489a066")
        @@index([_shard, namespace, status, lastAttemptAt], map: "idx_fragno_hooks_idx_namespace_status_last_attempt_f6aacab3")
        @@index([_shard, namespace, status, nextRetryAt], map: "idx_fragno_hooks_idx_namespace_status_retry_b66b1168")
        @@index([_shard, nonce], map: "idx_fragno_hooks_idx_nonce_90c97cf1")
        @@unique([_shard, id], map: "uidx_fragno_hooks__fragno_fragno_hooks_shard_external_ide396e3b")
        @@unique([_shard, _internalId], map: "uidx_fragno_hooks__fragno_fragno_hooks_shard_internal_i9c5d8377")
        @@map("fragno_hooks")
      }

      model Posts_blog {
        id String @default(cuid())
        title String
        authorId Int
        editorId Int?
        publishedAt Int?
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        author Users_blog @relation("blog_posts_author_users", fields: [_shard, authorId], references: [_shard, _internalId], map: "fk_posts_users_posts_authorId_fk_blog_7969e40f")
        editor Users_blog? @relation("blog_posts_editor_users", fields: [_shard, editorId], references: [_shard, _internalId], map: "fk_posts_users_posts_editorId_fk_blog_3e07e080")
        @@index([_shard, title], map: "idx_posts_idx_title_blog_f90cbb7e")
        @@unique([_shard, id], map: "uidx_posts__fragno_posts_shard_external_id_blog_1548d897")
        @@unique([_shard, _internalId], map: "uidx_posts__fragno_posts_shard_internal_id_blog_68dfcd25")
        @@map("posts_blog")
      }

      model Users_blog {
        id String @default(cuid())
        email String
        createdAt Int @default(dbgenerated("CURRENT_TIMESTAMP"))
        birthDate Int?
        profile Json?
        bigScore Bytes
        reputation Float
        invitedBy Int?
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        invitedBy_1 Users_blog? @relation("blog_users_invitedBy_users", fields: [_shard, invitedBy], references: [_shard, _internalId], map: "fk_users_users_users_invitedBy_fk_blog_2f6bd5fd")
        posts Posts_blog[] @relation("blog_posts_author_users")
        posts_editor Posts_blog[] @relation("blog_posts_editor_users")
        users Users_blog[] @relation("blog_users_invitedBy_users")
        @@unique([_shard, email], map: "uidx_users_idx_email_blog_4468050e")
        @@unique([_shard, id], map: "uidx_users__fragno_users_shard_external_id_blog_347b9685")
        @@unique([_shard, _internalId], map: "uidx_users__fragno_users_shard_internal_id_blog_1020970d")
        @@map("users_blog")
      }"
    `);
  });

  it("should skip join-only relations in Prisma output", () => {
    const joinOnlySchema = schema("joinonly", (s) => {
      return s
        .addTable("users", (t) => {
          return t
            .addColumn("id", idColumn())
            .addColumn("email", column("string"))
            .createIndex("idx_users_email", ["email"]);
        })
        .addTable("invitations", (t) => {
          return t
            .addColumn("id", idColumn())
            .addColumn("email", column("string"))
            .createIndex("idx_inv_email", ["email"]);
        });
    });

    const generated = generatePrismaSchema(
      [{ namespace: "joinonly", schema: joinOnlySchema }],
      "sqlite",
      { sqliteStorageMode: sqliteStoragePrisma },
    );

    expect(generated).not.toContain("@relation(");
  });

  it("should generate PostgreSQL (PGLite) Prisma schema", () => {
    const generated = generatePrismaSchema(
      [
        { namespace: null, schema: internalSchema },
        { namespace: "blog", schema: blogSchema },
      ],
      "postgresql",
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.
      // Provider: postgresql
      // Namespaces: blog

      model FragnoDbOutbox {
        id String @default(cuid()) @db.VarChar(128)
        versionstamp String @db.VarChar(191)
        uowId String @db.VarChar(191)
        payload Json @db.Json
        refMap Json? @db.Json
        createdAt DateTime @default(now())
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        @@index([_shard, uowId], map: "idx_outbox_uow")
        @@unique([_shard, versionstamp], map: "idx_outbox_versionstamp")
        @@unique([_shard, id], map: "_fragno_fragno_db_outbox_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_fragno_db_outbox_shard_internal_id")
        @@map("fragno_db_outbox")
      }

      model FragnoDbOutboxMutations {
        id String @default(cuid()) @db.VarChar(128)
        entryVersionstamp String @db.VarChar(191)
        mutationVersionstamp String @db.VarChar(191)
        uowId String @db.VarChar(191)
        schema String @db.VarChar(191)
        table String @db.VarChar(191)
        externalId String? @db.VarChar(191)
        op String @db.VarChar(191)
        createdAt DateTime @default(now())
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        payload Json @db.Json
        @@index([_shard, entryVersionstamp], map: "idx_outbox_mutations_entry")
        @@index([_shard, entryVersionstamp, mutationVersionstamp], map: "idx_outbox_mutations_entry_order")
        @@index([_shard, schema, table, externalId, entryVersionstamp], map: "idx_outbox_mutations_key")
        @@index([_shard, uowId], map: "idx_outbox_mutations_uow")
        @@unique([_shard, id], map: "_fragno_fragno_db_outbox_mutations_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_fragno_db_outbox_mutations_shard_internal_id")
        @@map("fragno_db_outbox_mutations")
      }

      model FragnoDbSettings {
        id String @default(cuid()) @db.VarChar(128)
        key String @db.VarChar(191)
        value String @db.Text
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        @@unique([_shard, key], map: "unique_key")
        @@unique([_shard, id], map: "_fragno_fragno_db_settings_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_fragno_db_settings_shard_internal_id")
        @@map("fragno_db_settings")
      }

      model FragnoDbSyncRequests {
        id String @default(cuid()) @db.VarChar(128)
        requestId String @db.VarChar(191)
        status String @db.VarChar(191)
        confirmedCommandIds Json @db.Json
        conflictCommandId String? @db.VarChar(191)
        baseVersionstamp String? @db.VarChar(191)
        lastVersionstamp String? @db.VarChar(191)
        createdAt DateTime @default(now())
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        @@unique([_shard, requestId], map: "idx_sync_request_id")
        @@unique([_shard, id], map: "_fragno_fragno_db_sync_requests_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_fragno_db_sync_requests_shard_internal_id")
        @@map("fragno_db_sync_requests")
      }

      model FragnoHooks {
        id String @default(cuid()) @db.VarChar(128)
        namespace String @db.VarChar(191)
        hookName String @db.VarChar(191)
        payload Json @db.Json
        status String @db.VarChar(191)
        attempts Int @default(0)
        maxAttempts Int @default(5)
        lastAttemptAt DateTime?
        nextRetryAt DateTime?
        error String? @db.Text
        createdAt DateTime @default(now())
        nonce String @db.VarChar(191)
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        propagationContext Json? @db.Json
        @@index([_shard, namespace, createdAt, id], map: "idx_namespace_created_at")
        @@index([_shard, namespace, status, lastAttemptAt], map: "idx_namespace_status_last_attempt")
        @@index([_shard, namespace, status, nextRetryAt], map: "idx_namespace_status_retry")
        @@index([_shard, nonce], map: "idx_nonce")
        @@unique([_shard, id], map: "_fragno_fragno_hooks_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_fragno_hooks_shard_internal_id")
        @@map("fragno_hooks")
      }

      model Posts_blog {
        id String @default(cuid()) @db.VarChar(128)
        title String @db.VarChar(191)
        authorId BigInt
        editorId BigInt?
        publishedAt DateTime?
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        author Users_blog @relation("blog_posts_author_users", fields: [_shard, authorId], references: [_shard, _internalId], map: "fk_posts_users_posts_authorId_fk")
        editor Users_blog? @relation("blog_posts_editor_users", fields: [_shard, editorId], references: [_shard, _internalId], map: "fk_posts_users_posts_editorId_fk")
        @@index([_shard, title], map: "idx_title")
        @@unique([_shard, id], map: "_fragno_posts_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_posts_shard_internal_id")
        @@map("posts")
      }

      model Users_blog {
        id String @default(cuid()) @db.VarChar(128)
        email String @db.VarChar(191)
        createdAt DateTime @default(now())
        birthDate DateTime? @db.Date
        profile Json? @db.Json
        bigScore BigInt
        reputation Decimal
        invitedBy BigInt?
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        invitedBy_1 Users_blog? @relation("blog_users_invitedBy_users", fields: [_shard, invitedBy], references: [_shard, _internalId], map: "fk_users_users_users_invitedBy_fk")
        posts Posts_blog[] @relation("blog_posts_author_users")
        posts_editor Posts_blog[] @relation("blog_posts_editor_users")
        users Users_blog[] @relation("blog_users_invitedBy_users")
        @@unique([_shard, email], map: "idx_email")
        @@unique([_shard, id], map: "_fragno_users_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_users_shard_internal_id")
        @@map("users")
      }"
    `);
  });

  it("should sanitize namespaces and map invalid identifiers for SQLite", () => {
    const generated = generatePrismaSchema(
      [{ namespace: "my-app", schema: weirdNamesSchema }],
      "sqlite",
      { sqliteStorageMode: sqliteStoragePrisma },
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.
      // Provider: sqlite
      // Namespaces: my-app

      model UserProfiles_my_app {
        id String @default(cuid())
        user_id String @map("user-id")
        display_name String? @map("display name")
        _internalId Int @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("")
        @@index([_shard, user_id], map: "idx_user-profiles_user-id-index_my-app_c295d8f4")
        @@unique([_shard, id], map: "uidx_user-profiles__fragno_user-profiles_shard_external31b87c7e")
        @@unique([_shard, _internalId], map: "uidx_user-profiles__fragno_user-profiles_shard_internal5f547362")
        @@map("user-profiles_my-app")
      }"
    `);
  });

  it("should sanitize namespaces and map invalid identifiers for PostgreSQL", () => {
    const generated = generatePrismaSchema(
      [{ namespace: "my-app", schema: weirdNamesSchema }],
      "postgresql",
    );

    expect(generated).toMatchInlineSnapshot(`
      "// Generated by Fragno Prisma adapter.
      // Provider: postgresql
      // Namespaces: my-app

      model UserProfiles_my_app {
        id String @default(cuid()) @db.VarChar(128)
        user_id String @db.VarChar(191) @map("user-id")
        display_name String? @db.VarChar(191) @map("display name")
        _internalId BigInt @id @default(autoincrement())
        _version Int @default(0)
        _shard String @default("") @db.VarChar(191)
        @@index([_shard, user_id], map: "user-id-index")
        @@unique([_shard, id], map: "_fragno_user-profiles_shard_external_id")
        @@unique([_shard, _internalId], map: "_fragno_user-profiles_shard_internal_id")
        @@map("user-profiles")
      }"
    `);
  });

  it("should disambiguate inverse relations for SQLite", () => {
    const generated = generatePrismaSchema(
      [{ namespace: "test", schema: relationNamingSchema }],
      "sqlite",
      { sqliteStorageMode: sqliteStoragePrisma },
    );

    expect(generated).toContain('posts Posts_test[] @relation("test_posts_author_users")');
    expect(generated).toContain('posts_editor Posts_test[] @relation("test_posts_editor_users")');
    expect(generated).toContain('comments Comments_test[] @relation("test_comments_post_posts")');
    expect(generated).toContain(
      'comments Comments_test[] @relation("test_comments_parent_comments")',
    );
    expect(generated).toContain('follows Follows_test[] @relation("test_follows_followee_users")');
    expect(generated).toContain(
      'follows_follower Follows_test[] @relation("test_follows_follower_users")',
    );
  });

  it("should disambiguate inverse relations for PostgreSQL", () => {
    const generated = generatePrismaSchema(
      [{ namespace: "test", schema: relationNamingSchema }],
      "postgresql",
    );

    expect(generated).toContain('posts Posts_test[] @relation("test_posts_author_users")');
    expect(generated).toContain('posts_editor Posts_test[] @relation("test_posts_editor_users")');
    expect(generated).toContain('comments Comments_test[] @relation("test_comments_post_posts")');
    expect(generated).toContain(
      'comments Comments_test[] @relation("test_comments_parent_comments")',
    );
    expect(generated).toContain('follows Follows_test[] @relation("test_follows_followee_users")');
    expect(generated).toContain(
      'follows_follower Follows_test[] @relation("test_follows_follower_users")',
    );
  });
});
