import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { format, type FormatOptions } from "oxfmt";

import { createStaticContextOverviewMarkdown } from "./static-context-overview.js";

const GENERATED_FILE_NOTICE =
  "<!-- Generated by `pnpm backoffice:context`. Do not edit manually. -->\n\n";

type ContextGraphFileResult =
  | { kind: "written"; outputFile: string }
  | { kind: "current"; outputFile: string }
  | { kind: "stale"; outputFile: string };

function isFileNotFoundError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}

async function readExistingContextGraph(outputFile: string): Promise<string | null> {
  try {
    return await readFile(outputFile, "utf8");
  } catch (error) {
    if (isFileNotFoundError(error)) {
      return null;
    }
    throw error;
  }
}

/** Writes or verifies the checked-in Backoffice context graph Markdown file. */
export async function updateBackofficeContextGraphFile({
  staticDirectory,
  outputFile,
  mode,
  formatterOptions,
}: {
  staticDirectory: string;
  outputFile: string;
  mode: "write" | "check";
  formatterOptions: FormatOptions;
}): Promise<ContextGraphFileResult> {
  const absoluteOutputFile = resolve(outputFile);
  const unformattedContent = `${GENERATED_FILE_NOTICE}${await createStaticContextOverviewMarkdown(
    staticDirectory,
  )}`;
  const formatResult = await format(absoluteOutputFile, unformattedContent, formatterOptions);
  if (formatResult.errors.length > 0) {
    const messages = formatResult.errors.map((error) => error.message).join("; ");
    throw new Error(`Backoffice context graph Markdown formatting failed: ${messages}`);
  }
  const expectedContent = formatResult.code;

  if (mode === "check") {
    const existingContent = await readExistingContextGraph(absoluteOutputFile);
    return existingContent === expectedContent
      ? { kind: "current", outputFile: absoluteOutputFile }
      : { kind: "stale", outputFile: absoluteOutputFile };
  }

  await mkdir(dirname(absoluteOutputFile), { recursive: true });
  await writeFile(absoluteOutputFile, expectedContent);
  return { kind: "written", outputFile: absoluteOutputFile };
}
