import { afterEach, assert, describe, expect, it } from "vitest";

import { execFileSync, spawnSync } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { updateBackofficeContextGraphFile } from "./context-graph-file";
import { createStaticContextOverviewMarkdown } from "./static-context-overview";

const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(packageDirectory, "../..");
const temporaryDirectories: string[] = [];
const markdownFormatterOptions = { printWidth: 100, proseWrap: "always" } as const;

async function writeFixtureFile(root: string, path: string, content: string): Promise<void> {
  const destination = resolve(root, path);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, content);
}

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true })),
  );
});

describe("Backoffice static context overview", () => {
  it("expands codemode declarations and follows skill references", async () => {
    const root = await mkdtemp(resolve(tmpdir(), "backoffice-context-"));
    temporaryDirectories.push(root);

    await writeFixtureFile(
      root,
      "SYSTEM.md",
      "# Test system\n\nRead /static/codemode/providers/state.d.ts.\n\n__BACKOFFICE_CODEMODE_DTS__;\n",
    );
    await writeFixtureFile(
      root,
      "codemode/system.d.ts",
      '/// <reference path="/static/codemode/providers/state.d.ts" />\n/// <reference path="/static/codemode/providers/events.d.ts" />\n',
    );
    await writeFixtureFile(
      root,
      "codemode/providers/state.d.ts",
      "// state tools\ntype State = {};\n",
    );
    await writeFixtureFile(
      root,
      "codemode/providers/events.d.ts",
      "// events tools\ntype Events = {};\n",
    );
    await writeFixtureFile(
      root,
      "skills/example/SKILL.md",
      `---\nname: example\ndescription:\n  Load example context when the user asks for an example.\n---\n\n# Example skill\n\nRead /static/skills/example/reference.md.\n`,
    );
    await writeFixtureFile(
      root,
      "skills/example/reference.md",
      "# Example reference\n\nContinue with [details](details.md).\n",
    );
    await writeFixtureFile(root, "skills/example/details.md", "# Example details\n");
    await writeFixtureFile(root, "docs/unreferenced.md", "# Unreferenced\n");

    const output = await createStaticContextOverviewMarkdown(root);

    expect(output).toContain("# Backoffice static agent-context graph");
    expect(output).toContain("## System entry point\n\n```text");
    expect(output).toContain(
      "__BACKOFFICE_CODEMODE_DTS__ expands from /static/codemode/system.d.ts",
    );
    expect(output).toContain("/static/codemode/providers/events.d.ts — events tools");
    expect(output).toContain(
      "> **Load when:** Load example context when the user asks for an example.",
    );
    expect(output).toContain("/static/skills/example/details.md — Example details");
    expect(output).toContain("- `/static/docs/unreferenced.md`");
  });

  it("writes and checks the generated Markdown file", async () => {
    const root = await mkdtemp(resolve(tmpdir(), "backoffice-context-file-"));
    temporaryDirectories.push(root);
    const staticDirectory = resolve(root, "static");
    const outputFile = resolve(root, "content/CONTEXT-GRAPH.md");
    await writeFixtureFile(staticDirectory, "SYSTEM.md", "# Test system\n");

    await expect(
      updateBackofficeContextGraphFile({
        staticDirectory,
        outputFile,
        mode: "write",
        formatterOptions: markdownFormatterOptions,
      }),
    ).resolves.toEqual({ kind: "written", outputFile });
    expect(await readFile(outputFile, "utf8")).toContain(
      "<!-- Generated by `pnpm backoffice:context`. Do not edit manually. -->",
    );
    await expect(
      updateBackofficeContextGraphFile({
        staticDirectory,
        outputFile,
        mode: "check",
        formatterOptions: markdownFormatterOptions,
      }),
    ).resolves.toEqual({ kind: "current", outputFile });

    await writeFixtureFile(staticDirectory, "SYSTEM.md", "# Changed system\n");
    await expect(
      updateBackofficeContextGraphFile({
        staticDirectory,
        outputFile,
        mode: "check",
        formatterOptions: markdownFormatterOptions,
      }),
    ).resolves.toEqual({ kind: "stale", outputFile });
  });

  it("requires the generated graph to be staged for pre-commit checks", async () => {
    const indexDirectory = await mkdtemp(resolve(tmpdir(), "backoffice-context-index-"));
    temporaryDirectories.push(indexDirectory);
    const environment = {
      ...process.env,
      GIT_INDEX_FILE: resolve(indexDirectory, "index"),
    };
    const script = resolve(repositoryRoot, "scripts/generate-backoffice-context-graph.ts");
    const tsx = resolve(repositoryRoot, "node_modules/.bin/tsx");

    execFileSync("git", ["read-tree", "HEAD"], { cwd: repositoryRoot, env: environment });
    const unstagedResult = spawnSync(tsx, [script, "--check-staged"], {
      cwd: repositoryRoot,
      env: environment,
      encoding: "utf8",
    });
    assert.equal(unstagedResult.status, 1);
    expect(unstagedResult.stderr).toContain("Staged Backoffice context graph is stale or missing");

    execFileSync("git", ["add", "--", "content/CONTEXT-GRAPH.md"], {
      cwd: repositoryRoot,
      env: environment,
    });
    const stagedResult = spawnSync(tsx, [script, "--check-staged"], {
      cwd: repositoryRoot,
      env: environment,
      encoding: "utf8",
    });
    assert.equal(stagedResult.status, 0);
    expect(stagedResult.stdout).toContain("Backoffice context graph is up to date");
  });

  it("ships an executable with approachable help", () => {
    const output = execFileSync(
      process.execPath,
      [resolve(packageDirectory, "bin/run.js"), "--help"],
      {
        cwd: packageDirectory,
        encoding: "utf8",
      },
    );

    expect(output).toContain("Usage:");
    expect(output).toContain("backoffice-context [static-directory]");
  });
});
