import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "./src/mod.ts",
    "./src/id.ts",
    "./src/schema/create.ts",
    "./src/query/simple-query-interface.ts",
    "./src/adapters/adapters.ts",
    "./src/adapters/kysely/kysely-adapter.ts",
    "./src/adapters/drizzle/drizzle-adapter.ts",
    "./src/adapters/drizzle/generate.ts",
    "./src/adapters/prisma/prisma-adapter.ts",
    "./src/adapters/prisma/generate.ts",
    "./src/adapters/in-memory/index.ts",
    "./src/adapters/generic-sql/generic-sql-adapter.ts",
    "./src/adapters/generic-sql/driver-config.ts",
    "./src/sql-driver/sql-driver.ts",
    "./src/sql-driver/dialects/dialects.ts",
    "./src/sql-driver/dialects/durable-object-dialect.ts",
    "./src/query/unit-of-work/unit-of-work.ts",
    "./src/query/cursor.ts",
    "./src/fragment.ts",
    "./src/db-fragment-definition-builder.ts",
    "./src/dispatchers/node/index.ts",
    "./src/dispatchers/cloudflare-do/index.ts",
    "./src/migration-engine/generation-engine.ts",
  ],
  dts: true,
  unbundle: true,
});
