#!/bin/sh

# Commit messages must adhere to https://www.conventionalcommits.org/
# This script is adapted from: https://github.com/joaobsjunior/sh-conventional-commits/blob/main/commit-msg


# Regex to validate the type pattern
REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"

FILE=`cat $1` # File containing the commit message

echo "Commit Message: ${FILE}"

if ! [[ $FILE =~ $REGEX ]]; then
	echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard (https://www.conventionalcommits.org). ​"
	exit 1
else
	echo >&2 "Valid commit message."
fi
