import {
  isRouteErrorResponse,
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "react-router";
import { RootProvider } from "fumadocs-ui/provider/react-router";
import type { Route } from "./+types/root";

import "./app.css";

export const links: Route.LinksFunction = () => [
  { rel: "preconnect", href: "https://fonts.googleapis.com" },
  {
    rel: "preconnect",
    href: "https://fonts.gstatic.com",
    crossOrigin: "anonymous",
  },
  {
    rel: "stylesheet",
    href: "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap",
  },
];

/**
 * URL redirects for documentation refactor
 * Generated by LLM by passing old and new sitemap.xml
 * The refactor split the documentation up into two "layers", fragno and stripe.
 */
const REDIRECTS: Record<string, string> = {
  // Stripe fragment: /docs/our-fragments/stripe/* -> /docs/stripe/*
  "/docs/our-fragments/stripe/admin-hooks": "/docs/stripe/admin-hooks",
  "/docs/our-fragments/stripe/quickstart": "/docs/stripe/quickstart",
  "/docs/our-fragments/stripe/subscriptions": "/docs/stripe/subscriptions",
  "/docs/our-fragments/stripe/webhooks": "/docs/stripe/webhooks",

  // Framework docs: /docs/* -> /docs/fragno/*
  "/docs/frameworks": "/docs/fragno/reference/frameworks",
  "/docs/user-quick-start": "/docs/fragno/user-quick-start",
  "/docs/for-library-authors/faq": "/docs/fragno/for-library-authors/faq",
  "/docs/for-library-authors/getting-started": "/docs/fragno/for-library-authors/getting-started",
  "/docs/for-library-authors/testing": "/docs/fragno/for-library-authors/testing",
  "/docs/for-library-authors/troubleshooting": "/docs/fragno/for-library-authors/troubleshooting",
  "/docs/for-users/client-customization": "/docs/fragno/for-users/client-customization",
  "/docs/for-users/integrating-a-fragment": "/docs/fragno/for-users/integrating-a-fragment",
  "/docs/for-users/middleware": "/docs/fragno/for-users/middleware",
  "/docs/for-users/services": "/docs/fragno/for-users/services",
  "/docs/reference/cli": "/docs/fragno/reference/cli",
  "/docs/reference/frameworks": "/docs/fragno/reference/frameworks",
  "/docs/reference/glossary": "/docs/fragno/reference/glossary",
  "/docs/for-library-authors/database-integration/defining-schemas":
    "/docs/fragno/for-library-authors/database-integration/defining-schemas",
  "/docs/for-library-authors/database-integration/overview":
    "/docs/fragno/for-library-authors/database-integration/overview",
  "/docs/for-library-authors/database-integration/querying":
    "/docs/fragno/for-library-authors/database-integration/querying",
  "/docs/for-library-authors/features/client-state-management":
    "/docs/fragno/for-library-authors/features/client-state-management",
  "/docs/for-library-authors/features/code-splitting":
    "/docs/fragno/for-library-authors/features/code-splitting",
  "/docs/for-library-authors/features/dependencies-and-services":
    "/docs/fragno/for-library-authors/features/dependencies-and-services",
  "/docs/for-library-authors/features/route-definition":
    "/docs/fragno/for-library-authors/features/route-definition",
  "/docs/for-users/client-frameworks/react": "/docs/fragno/for-users/client-frameworks/react",
  "/docs/for-users/client-frameworks/solid-js": "/docs/fragno/for-users/client-frameworks/solid-js",
  "/docs/for-users/client-frameworks/svelte": "/docs/fragno/for-users/client-frameworks/svelte",
  "/docs/for-users/client-frameworks/vanilla-js":
    "/docs/fragno/for-users/client-frameworks/vanilla-js",
  "/docs/for-users/client-frameworks/vue": "/docs/fragno/for-users/client-frameworks/vue",
  "/docs/for-users/database-fragments/drizzle": "/docs/fragno/for-users/database-fragments/drizzle",
  "/docs/for-users/database-fragments/kysely": "/docs/fragno/for-users/database-fragments/kysely",
  "/docs/for-users/database-fragments/overview":
    "/docs/fragno/for-users/database-fragments/overview",
};

const serverMiddleware: Route.MiddlewareFunction = async ({ request }, next) => {
  const url = new URL(request.url);

  // Check for redirects
  const redirectTarget = REDIRECTS[url.pathname];
  if (redirectTarget) {
    const destination = new URL(redirectTarget, url);
    return Response.redirect(destination, 308);
  }

  return next();
};

export const middleware = [serverMiddleware];

export function Layout({ children }: { children: React.ReactNode }) {
  const baseUrl =
    process.env.NODE_ENV === "development" ? "http://localhost:3000" : "https://fragno.dev";
  const description =
    "Fragno is the toolkit for building full-stack TypeScript libraries that work seamlessly across frameworks";
  const socialImage = `${baseUrl}/social.webp`;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={description} />
        <meta property="og:title" content="Fragno" />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={socialImage} />
        <meta property="og:url" content={baseUrl} />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Fragno" />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={socialImage} />
        <Meta />
        <Links />
      </head>
      <body className="flex min-h-screen flex-col">
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  return (
    <RootProvider>
      <Outlet />
    </RootProvider>
  );
}

export function ErrorBoundary({ error }: Route.ErrorBoundaryProps) {
  let message = "Oops!";
  let details = "An unexpected error occurred.";
  let stack: string | undefined;

  if (isRouteErrorResponse(error)) {
    message = error.status === 404 ? "404" : "Error";
    details =
      error.status === 404 ? "The requested page could not be found." : error.statusText || details;
  } else if (import.meta.env.DEV && error && error instanceof Error) {
    details = error.message;
    stack = error.stack;
  }

  return (
    <main className="container mx-auto p-4 pt-16">
      <h1>{message}</h1>
      <p>{details}</p>
      {stack && (
        <pre className="w-full overflow-x-auto p-4">
          <code>{stack}</code>
        </pre>
      )}
    </main>
  );
}
