import {
  backofficeCapabilities,
  type BackofficeCapabilityId,
} from "@/fragno/backoffice-capabilities/backoffice-capabilities";
import {
  renderMcpCodemodeProviderTypes,
  type McpCodemodeServer,
} from "@/fragno/codemode/mcp-codemode-tools";
import {
  createRuntimeToolReferences,
  renderCodemodeProviderTypes,
  renderCodemodeWorkflowTypes,
} from "@/fragno/runtime-tools/reference";
import type { BackofficeRuntimeToolFamily } from "@/fragno/runtime-tools/runtime-tools";

export const CODEMODE_DTS_PATH = "/workspace/codemode.d.ts";

const ALWAYS_AVAILABLE_CODEMODE_NAMESPACES = new Set([
  "capabilities",
  "connections",
  "store",
  "workflow",
  "hooks",
  "events",
  "event",
  "otp",
]);

const VALID_DECLARE_CONST_NAME = /^[A-Za-z_$][\w$]*$/u;

const getCapabilityRuntimeNamespaces = (
  capabilityId: BackofficeCapabilityId,
): readonly string[] => {
  const capability = backofficeCapabilities.find((candidate) => candidate.id === capabilityId);
  return capability?.runtimeToolNamespaces ?? [];
};

export const createCodemodeDts = ({
  configuredCapabilityIds = [],
  families,
  mcpServers = [],
  stateTypes,
}: {
  configuredCapabilityIds?: readonly BackofficeCapabilityId[];
  families: readonly BackofficeRuntimeToolFamily[];
  mcpServers?: readonly McpCodemodeServer[];
  stateTypes: string;
}) => {
  const dynamicNamespaces = new Set<string>();
  for (const capabilityId of configuredCapabilityIds) {
    for (const namespace of getCapabilityRuntimeNamespaces(capabilityId)) {
      dynamicNamespaces.add(namespace);
    }
  }

  const allowedNamespaces = new Set([
    ...ALWAYS_AVAILABLE_CODEMODE_NAMESPACES,
    ...dynamicNamespaces,
  ]);

  const references = createRuntimeToolReferences({
    families: families
      .filter((family) => !family.hidden)
      .map((family) => ({
        ...family,
        tools: family.tools.filter(
          (tool) =>
            VALID_DECLARE_CONST_NAME.test(tool.namespace) && allowedNamespaces.has(tool.namespace),
        ),
      }))
      .filter((family) => family.tools.length > 0),
  });

  const providerTypes = references.length ? `\n\n${renderCodemodeProviderTypes(references)}` : "";
  const mcpProviderTypes = renderMcpCodemodeProviderTypes(mcpServers);
  return [
    "// Generated by Backoffice system automation. Do not edit manually.",
    "// Source of truth: configured Backoffice capabilities and cached MCP server tools.",
    "",
    stateTypes,
    "",
    renderCodemodeWorkflowTypes(),
    providerTypes.trimStart(),
    mcpProviderTypes,
    "",
  ]
    .filter(Boolean)
    .join("\n");
};
